Repository HMDandelion/project1-4-1000-2_back, pull requests merged in 2024-05, with the labels that each got.

#3 Enhancement/1 프로젝트기초세팅
  src/main/java/com/hmdandelion/project_1410002/dashboard/presentation/DashboardController.java
  src/main/java/com/hmdandelion/project_1410002/inventory/domian/entity/material/MaterialStock.java
  src/main/java/com/hmdandelion/project_1410002/inventory/domian/repository/material/MaterialStockRepo.java
  src/main/java/com/hmdandelion/project_1410002/inventory/dto/material/MaterialStockDTO.java
  src/main/java/com/hmdandelion/project_1410002/inventory/presentation/MaterialStockController.java
  src/main/java/com/hmdandelion/project_1410002/inventory/service/MaterialStockService.java
  src/main/java/com/hmdandelion/project_1410002/material/domain/entity/MaterialSpec.java
  src/main/java/com/hmdandelion/project_1410002/production/domain/entity/material/MaterialUsage.java
  src/main/java/com/hmdandelion/project_1410002/production/domain/repository/material/MaterialUsageRepo.java
  src/main/java/com/hmdandelion/project_1410002/production/presentation/MaterialUsageController.java
  src/main/java/com/hmdandelion/project_1410002/production/service/MaterialUsageService.java
  src/main/java/com/hmdandelion/project_1410002/purchase/domain/entity/material/MaterialOrder.java
  src/main/java/com/hmdandelion/project_1410002/purchase/domain/repository/material/MaterialOrderRepo.java
  src/main/java/com/hmdandelion/project_1410002/purchase/presentation/MaterialOrderController.java
  src/main/java/com/hmdandelion/project_1410002/purchase/service/MaterialOrderService.java
  src/main/java/com/hmdandelion/project_1410002/sales/domain/entity/client/Client.java
  src/main/java/com/hmdandelion/project_1410002/sales/domain/repository/client/ClientRepo.java
  src/main/java/com/hmdandelion/project_1410002/sales/model/ClientStatus.java
  src/main/java/com/hmdandelion/project_1410002/sales/model/ClientType.java
  src/main/java/com/hmdandelion/project_1410002/sales/presentation/ClientController.java
  src/main/java/com/hmdandelion/project_1410002/sales/service/ClientService.java
Labels: PR

#15 [PR] 거래처 관리 구현
  src/main/java/com/hmdandelion/project_1410002/sales/domain/entity/client/Client.java
  src/main/java/com/hmdandelion/project_1410002/sales/domain/entity/order/Order.java
  src/main/java/com/hmdandelion/project_1410002/sales/domain/entity/order/OrderProduct.java
  src/main/java/com/hmdandelion/project_1410002/sales/domain/repository/client/ClientRepo.java
  src/main/java/com/hmdandelion/project_1410002/sales/domain/repository/client/ClientRepoCustom.java
  src/main/java/com/hmdandelion/project_1410002/sales/domain/repository/client/ClientRepoCustomImpl.java
  src/main/java/com/hmdandelion/project_1410002/sales/domain/repository/order/OrderRepo.java
  src/main/java/com/hmdandelion/project_1410002/sales/domain/type/ClientStatus.java
  src/main/java/com/hmdandelion/project_1410002/sales/domain/type/ClientType.java
  src/main/java/com/hmdandelion/project_1410002/sales/domain/type/OrderStatus.java
  src/main/java/com/hmdandelion/project_1410002/sales/dto/request/ClientCreateRequest.java
  src/main/java/com/hmdandelion/project_1410002/sales/dto/request/ClientUpdateRequest.java
  src/main/java/com/hmdandelion/project_1410002/sales/dto/response/ClientOrderDTO.java
  src/main/java/com/hmdandelion/project_1410002/sales/dto/response/SalesClientResponse.java
  src/main/java/com/hmdandelion/project_1410002/sales/dto/response/SalesClientsResponse.java
  src/main/java/com/hmdandelion/project_1410002/sales/model/ClientStatus.java
  src/main/java/com/hmdandelion/project_1410002/sales/model/ClientType.java
  src/main/java/com/hmdandelion/project_1410002/sales/presentation/ClientController.java
  src/main/java/com/hmdandelion/project_1410002/sales/service/ClientService.java
Labels: feature

#14 [PR] 생산 계획 관리 구현
  DB/table.sql
  src/main/java/com/hmdandelion/project_1410002/OnlyForTest.java
  src/main/java/com/hmdandelion/project_1410002/Project1410002Application.java
  src/main/java/com/hmdandelion/project_1410002/common/exception/type/ExceptionCode.java
  src/main/java/com/hmdandelion/project_1410002/production/domain/entity/PlannedOrderList.java
  src/main/java/com/hmdandelion/project_1410002/production/domain/entity/ProductionPlan.java
  src/main/java/com/hmdandelion/project_1410002/production/domain/entity/ProductionPlannedList.java
  src/main/java/com/hmdandelion/project_1410002/production/domain/entity/WorkOrder.java
  src/main/java/com/hmdandelion/project_1410002/production/domain/repository/ProductionPlanRepo.java
  src/main/java/com/hmdandelion/project_1410002/production/domain/type/WorkOrderStatusType.java
  src/main/java/com/hmdandelion/project_1410002/production/dto/request/ProductionPlanCreateRequest.java
  src/main/java/com/hmdandelion/project_1410002/production/dto/request/ProductionPlanUpdateRequest.java
  src/main/java/com/hmdandelion/project_1410002/production/dto/response/PlanListResponse.java
  src/main/java/com/hmdandelion/project_1410002/production/presentation/ProductionPlanController.java
  src/main/java/com/hmdandelion/project_1410002/production/service/PlanService.java
Labels: feature

#25 [PR] 견적 관리 구현
  httpTest/EstimateTest.http
  httpTest/SalesClientTest.http
  src/main/java/com/hmdandelion/project_1410002/common/config/QuerydslConfig.java
  src/main/java/com/hmdandelion/project_1410002/common/exception/type/ExceptionCode.java
  src/main/java/com/hmdandelion/project_1410002/sales/domain/entity/estimate/Estimate.java
  src/main/java/com/hmdandelion/project_1410002/sales/domain/entity/estimate/EstimateProduct.java
  src/main/java/com/hmdandelion/project_1410002/sales/domain/entity/order/Order.java
  src/main/java/com/hmdandelion/project_1410002/sales/domain/entity/order/OrderProduct.java
  src/main/java/com/hmdandelion/project_1410002/sales/domain/repository/estimate/EstimateProductRepo.java
  src/main/java/com/hmdandelion/project_1410002/sales/domain/repository/estimate/EstimateRepo.java
  src/main/java/com/hmdandelion/project_1410002/sales/domain/repository/estimate/EstimateRepoCustom.java
  src/main/java/com/hmdandelion/project_1410002/sales/domain/repository/estimate/EstimateRepoCustomImpl.java
  src/main/java/com/hmdandelion/project_1410002/sales/domain/type/EstimateStatus.java
  src/main/java/com/hmdandelion/project_1410002/sales/dto/request/EstimateCreateRequest.java
  src/main/java/com/hmdandelion/project_1410002/sales/dto/request/EstimateProductRequest.java
  src/main/java/com/hmdandelion/project_1410002/sales/dto/request/EstimateUpdateRequest.java
  src/main/java/com/hmdandelion/project_1410002/sales/dto/response/ClientOrderDTO.java
  src/main/java/com/hmdandelion/project_1410002/sales/dto/response/EstimateProductResponse.java
  src/main/java/com/hmdandelion/project_1410002/sales/dto/response/EstimateResponse.java
  src/main/java/com/hmdandelion/project_1410002/sales/dto/response/EstimatesResponse.java
  src/main/java/com/hmdandelion/project_1410002/sales/presentation/EstimateController.java
  src/main/java/com/hmdandelion/project_1410002/sales/service/ClientService.java
  src/main/java/com/hmdandelion/project_1410002/sales/service/EstimateService.java
Labels: feature, PR

#30 [PR] 창고 관련 기능
  src/main/java/com/hmdandelion/project_1410002/inventory/domian/repository/warehouse/WarehouseRepository.java
Labels: feature, PR

#32 [PR] 상품 스펙 관련 기능
  src/main/java/com/hmdandelion/project_1410002/inventory/domian/entity/product/ProductSpec.java
  src/main/java/com/hmdandelion/project_1410002/inventory/domian/repository/product/ProductRepoCustom.java
  src/main/java/com/hmdandelion/project_1410002/inventory/domian/repository/product/ProductRepoCustomImpl.java
  src/main/java/com/hmdandelion/project_1410002/inventory/domian/repository/product/ProductSpecRepo.java
  src/main/java/com/hmdandelion/project_1410002/inventory/dto/product/request/ProductRequest.java
  src/main/java/com/hmdandelion/project_1410002/inventory/dto/product/request/ProductSpecRequest.java
  src/main/java/com/hmdandelion/project_1410002/inventory/dto/product/response/ProductSpecResponse.java
  src/main/java/com/hmdandelion/project_1410002/inventory/presentation/ProductController.java
  src/main/java/com/hmdandelion/project_1410002/inventory/presentation/ProductSpecController.java
  src/main/java/com/hmdandelion/project_1410002/inventory/service/ProductService.java
  src/main/java/com/hmdandelion/project_1410002/inventory/service/ProductSpecService.java
  src/main/java/com/hmdandelion/project_1410002/inventory/service/WarehouseService.java
Labels: feature, PR

#34 #22 refactor : BOM기능 재 삽입
  src/main/java/com/hmdandelion/project_1410002/common/exception/type/ExceptionCode.java
  src/main/java/com/hmdandelion/project_1410002/inventory/domian/entity/product/Bom.java
  src/main/java/com/hmdandelion/project_1410002/inventory/domian/repository/product/BomRepo.java
  src/main/java/com/hmdandelion/project_1410002/inventory/dto/material/response/MaterialGraphRes.java
  src/main/java/com/hmdandelion/project_1410002/inventory/presentation/BomController.java
  src/main/java/com/hmdandelion/project_1410002/inventory/service/BomService.java
  src/main/java/com/hmdandelion/project_1410002/production/service/PlanService.java
Labels: enhancement, PR
