Repository HMDandelion/project1-4-1000-2_back, pull requests merged in 2024-06, with the labels that each got.

#36 [PR] 주문 및 반품 구현
  src/main/java/com/hmdandelion/project_1410002/common/exception/type/ExceptionCode.java
  src/main/java/com/hmdandelion/project_1410002/inventory/service/WarehouseService.java
  src/main/java/com/hmdandelion/project_1410002/sales/domain/entity/estimate/Estimate.java
  src/main/java/com/hmdandelion/project_1410002/sales/domain/entity/estimate/EstimateProduct.java
  src/main/java/com/hmdandelion/project_1410002/sales/domain/entity/order/Order.java
  src/main/java/com/hmdandelion/project_1410002/sales/domain/entity/order/OrderProduct.java
  src/main/java/com/hmdandelion/project_1410002/sales/domain/entity/returns/Return.java
  src/main/java/com/hmdandelion/project_1410002/sales/domain/entity/returns/ReturnProduct.java
  src/main/java/com/hmdandelion/project_1410002/sales/domain/repository/estimate/EstimateRepo.java
  src/main/java/com/hmdandelion/project_1410002/sales/domain/repository/order/OrderRepo.java
  src/main/java/com/hmdandelion/project_1410002/sales/domain/repository/order/OrderRepoCustom.java
  src/main/java/com/hmdandelion/project_1410002/sales/domain/repository/order/OrderRepoCustomImpl.java
  src/main/java/com/hmdandelion/project_1410002/sales/domain/repository/returns/ReturnRepo.java
  src/main/java/com/hmdandelion/project_1410002/sales/domain/repository/returns/ReturnRepoCustom.java
  src/main/java/com/hmdandelion/project_1410002/sales/domain/repository/returns/ReturnRepoCustomImpl.java
  src/main/java/com/hmdandelion/project_1410002/sales/domain/type/ManageStatus.java
  src/main/java/com/hmdandelion/project_1410002/sales/domain/type/ManageType.java
  src/main/java/com/hmdandelion/project_1410002/sales/domain/type/OrderStatus.java
  src/main/java/com/hmdandelion/project_1410002/sales/domain/type/ReturnStatus.java
  src/main/java/com/hmdandelion/project_1410002/sales/dto/request/ReturnCreateRequest.java
  src/main/java/com/hmdandelion/project_1410002/sales/dto/request/ReturnProductRequest.java
  src/main/java/com/hmdandelion/project_1410002/sales/dto/response/OrderClientDTO.java
  src/main/java/com/hmdandelion/project_1410002/sales/dto/response/OrderProductResponse.java
  src/main/java/com/hmdandelion/project_1410002/sales/dto/response/OrderResponse.java
  src/main/java/com/hmdandelion/project_1410002/sales/dto/response/OrdersResponse.java
  src/main/java/com/hmdandelion/project_1410002/sales/dto/response/ReturnsResponse.java
  src/main/java/com/hmdandelion/project_1410002/sales/presentation/OrderController.java
  src/main/java/com/hmdandelion/project_1410002/sales/presentation/ReturnController.java
  src/main/java/com/hmdandelion/project_1410002/sales/service/OrderService.java
  src/main/java/com/hmdandelion/project_1410002/sales/service/ReturnService.java
Labels: feature, PR

#38 [PR] 생산 및 검수 구현
  DB/table.sql
  build.gradle
  httpTest/ProductionReportTest.http
  src/main/java/com/hmdandelion/project_1410002/common/exception/type/ExceptionCode.java
  src/main/java/com/hmdandelion/project_1410002/production/domain/entity/line/Line.java
  src/main/java/com/hmdandelion/project_1410002/production/domain/entity/production/DefectDetail.java
  src/main/java/com/hmdandelion/project_1410002/production/domain/entity/production/ProductionDetail.java
  src/main/java/com/hmdandelion/project_1410002/production/domain/entity/production/ProductionManagement.java
  src/main/java/com/hmdandelion/project_1410002/production/domain/repository/production/DefectDetailRepo.java
  src/main/java/com/hmdandelion/project_1410002/production/domain/repository/production/ProductionDetailRepo.java
  src/main/java/com/hmdandelion/project_1410002/production/domain/repository/production/ProductionRepo.java
  src/main/java/com/hmdandelion/project_1410002/production/domain/type/DefectStatusType.java
  src/main/java/com/hmdandelion/project_1410002/production/domain/type/InspectionStatusType.java
  src/main/java/com/hmdandelion/project_1410002/production/domain/type/LineStatusType.java
  src/main/java/com/hmdandelion/project_1410002/production/domain/type/ProductionStatusType.java
  src/main/java/com/hmdandelion/project_1410002/production/dto/request/ProductionReportCreateRequest.java
  src/main/java/com/hmdandelion/project_1410002/production/dto/request/ProductionReportUpdateRequest.java
  src/main/java/com/hmdandelion/project_1410002/production/dto/response/production/DefectDetailResponse.java
  src/main/java/com/hmdandelion/project_1410002/production/dto/response/production/ProductionDetailResponse.java
  src/main/java/com/hmdandelion/project_1410002/production/dto/response/production/ProductionReportResponse.java
  src/main/java/com/hmdandelion/project_1410002/production/presentation/ProductionManagerController.java
  src/main/java/com/hmdandelion/project_1410002/production/service/ProductionService.java
  src/main/java/com/hmdandelion/project_1410002/sales/domain/entity/employee/Employee.java
  src/main/resources/application.yml
Labels: feature

#39 [PR] 반품 구현 완성
  httpTest/OrderTest.http
  httpTest/ReturnTest.http
  src/main/java/com/hmdandelion/project_1410002/common/exception/type/ExceptionCode.java
  src/main/java/com/hmdandelion/project_1410002/sales/domain/entity/returns/Return.java
  src/main/java/com/hmdandelion/project_1410002/sales/domain/repository/returns/ReturnRepo.java
  src/main/java/com/hmdandelion/project_1410002/sales/domain/repository/returns/ReturnRepoCustom.java
  src/main/java/com/hmdandelion/project_1410002/sales/domain/repository/returns/ReturnRepoCustomImpl.java
  src/main/java/com/hmdandelion/project_1410002/sales/domain/type/ReturnStatus.java
  src/main/java/com/hmdandelion/project_1410002/sales/dto/response/ExchangeOrderResponse.java
  src/main/java/com/hmdandelion/project_1410002/sales/dto/response/ReturnProductResponse.java
  src/main/java/com/hmdandelion/project_1410002/sales/dto/response/ReturnResponse.java
  src/main/java/com/hmdandelion/project_1410002/sales/presentation/ReturnController.java
  src/main/java/com/hmdandelion/project_1410002/sales/service/ReturnService.java
Labels: feature, PR

#42 [PR] 영업·판매 파트 리팩토링
  src/main/java/com/hmdandelion/project_1410002/common/exception/BadRequestException.java
  src/main/java/com/hmdandelion/project_1410002/common/exception/type/ExceptionCode.java
  src/main/java/com/hmdandelion/project_1410002/inventory/service/MaterialSpecService.java
  src/main/java/com/hmdandelion/project_1410002/sales/domain/repository/client/ClientRepoCustomImpl.java
  src/main/java/com/hmdandelion/project_1410002/sales/service/ClientService.java
  src/main/java/com/hmdandelion/project_1410002/sales/service/EstimateService.java
  src/main/java/com/hmdandelion/project_1410002/sales/service/OrderService.java
Labels: enhancement, PR

#50 [FIX] 오류 메세지 번호 변경
  src/main/java/com/hmdandelion/project_1410002/common/exception/type/ExceptionCode.java
  src/main/java/com/hmdandelion/project_1410002/common/exception/type/NotWarehouseException.java
  src/main/java/com/hmdandelion/project_1410002/inventory/service/WarehouseService.java
Labels: bug

#27 [PR] 작업 지시서 관리
  src/main/java/com/hmdandelion/project_1410002/common/exception/type/ExceptionCode.java
  src/main/java/com/hmdandelion/project_1410002/inventory/presentation/MaterialStockController.java
  src/main/java/com/hmdandelion/project_1410002/production/domain/entity/PlannedOrderList.java
  src/main/java/com/hmdandelion/project_1410002/production/domain/entity/ProductionPlan.java
  src/main/java/com/hmdandelion/project_1410002/production/domain/entity/ProductionPlannedList.java
  src/main/java/com/hmdandelion/project_1410002/production/domain/entity/WorkOrder.java
  src/main/java/com/hmdandelion/project_1410002/production/domain/entity/line/Line.java
  src/main/java/com/hmdandelion/project_1410002/production/domain/repository/productionPlan/ProductionPlanRepo.java
  src/main/java/com/hmdandelion/project_1410002/production/domain/repository/productionPlan/WorkOrderRepo.java
  src/main/java/com/hmdandelion/project_1410002/production/domain/repository/productionPlan/WorkOrderRepoCustom.java
  src/main/java/com/hmdandelion/project_1410002/production/domain/repository/productionPlan/WorkOrderRepoCustomImpl.java
  src/main/java/com/hmdandelion/project_1410002/production/domain/type/WorkOrderStatusType.java
  src/main/java/com/hmdandelion/project_1410002/production/dto/request/PlannedOrderListRequest.java
  src/main/java/com/hmdandelion/project_1410002/production/dto/request/ProductionPlanCreateRequest.java
  src/main/java/com/hmdandelion/project_1410002/production/dto/request/ProductionPlanUpdateRequest.java
  src/main/java/com/hmdandelion/project_1410002/production/dto/request/ProductionPlannedListRequest.java
  src/main/java/com/hmdandelion/project_1410002/production/dto/request/WorkOrderCreateRequest.java
  src/main/java/com/hmdandelion/project_1410002/production/dto/request/WorkOrderUpdateRequest.java
  src/main/java/com/hmdandelion/project_1410002/production/dto/response/PlanListResponse.java
  src/main/java/com/hmdandelion/project_1410002/production/dto/response/WorkOrderResponse.java
  src/main/java/com/hmdandelion/project_1410002/production/presentation/ProductionPlanController.java
  src/main/java/com/hmdandelion/project_1410002/production/presentation/WorkOrderController.java
  src/main/java/com/hmdandelion/project_1410002/production/service/PlanService.java
  src/main/java/com/hmdandelion/project_1410002/production/service/WorkOrderService.java
  src/main/java/com/hmdandelion/project_1410002/sales/domain/repository/estimate/EstimateRepoCustomImpl.java
Labels: feature

#47 [PR] 원자재 주문관리
  .github/pr-템플릿.md
  httpTest/MaterialClientTest.http
  httpTest/MaterialOrderTest.http
  src/main/java/com/hmdandelion/project_1410002/common/dto/response/material/MaterialObjectListResponse.java
  src/main/java/com/hmdandelion/project_1410002/common/exception/type/ExceptionCode.java
  src/main/java/com/hmdandelion/project_1410002/inventory/domian/entity/product/Bom.java
  src/main/java/com/hmdandelion/project_1410002/inventory/domian/repository/material/spec/MaterialSpecRepoCustom.java
  src/main/java/com/hmdandelion/project_1410002/inventory/domian/repository/material/spec/MaterialSpecRepoCustomImpl.java
  src/main/java/com/hmdandelion/project_1410002/inventory/domian/repository/material/stock/MaterialStockRepo.java
  src/main/java/com/hmdandelion/project_1410002/inventory/domian/repository/material/stock/MaterialStockRepoCustom.java
  src/main/java/com/hmdandelion/project_1410002/inventory/domian/repository/material/stock/MaterialStockRepoCustomImpl.java
  src/main/java/com/hmdandelion/project_1410002/inventory/domian/repository/warehouse/WarehouseRepo.java
  src/main/java/com/hmdandelion/project_1410002/inventory/dto/material/dto/MaterialGraphModel.java
  src/main/java/com/hmdandelion/project_1410002/inventory/dto/material/response/MaterialGraphResponse.java
  src/main/java/com/hmdandelion/project_1410002/inventory/presentation/MaterialAnalyzeController.java
  src/main/java/com/hmdandelion/project_1410002/inventory/service/MaterialAnalyzeService.java
  src/main/java/com/hmdandelion/project_1410002/inventory/service/MaterialSpecService.java
  src/main/java/com/hmdandelion/project_1410002/inventory/service/MaterialStockService.java
  src/main/java/com/hmdandelion/project_1410002/inventory/service/WarehouseService.java
  src/main/java/com/hmdandelion/project_1410002/production/domain/repository/ProductionPlannedListRepo.java
  src/main/java/com/hmdandelion/project_1410002/production/service/PlanService.java
  src/main/java/com/hmdandelion/project_1410002/production/service/ProductionPlannedListService.java
  src/main/java/com/hmdandelion/project_1410002/purchase/domain/entity/material/AssignedMaterial.java
  src/main/java/com/hmdandelion/project_1410002/purchase/domain/entity/material/MaterialOrder.java
  src/main/java/com/hmdandelion/project_1410002/purchase/domain/entity/material/OrderSpec.java
  src/main/java/com/hmdandelion/project_1410002/purchase/domain/repository/material/AssignedMaterialRepo.java
  src/main/java/com/hmdandelion/project_1410002/purchase/domain/repository/material/AssignedMaterialRepoCustom.java
  src/main/java/com/hmdandelion/project_1410002/purchase/domain/repository/material/AssignedMaterialRepoCustomImpl.java
  src/main/java/com/hmdandelion/project_1410002/purchase/domain/repository/material/MaterialOrderRepo.java
  src/main/java/com/hmdandelion/project_1410002/purchase/domain/repository/material/MaterialOrderRepoCustom.java
  src/main/java/com/hmdandelion/project_1410002/purchase/domain/repository/material/MaterialOrderRepoCustomImpl.java
  src/main/java/com/hmdandelion/project_1410002/purchase/dto/material/MaterialClientDTO.java
  src/main/java/com/hmdandelion/project_1410002/purchase/dto/material/MaterialOrderDTO.java
  src/main/java/com/hmdandelion/project_1410002/purchase/dto/material/OrderSpecCreateDTO.java
  src/main/java/com/hmdandelion/project_1410002/purchase/dto/material/request/MaterialClientCreateRequest.java
  src/main/java/com/hmdandelion/project_1410002/purchase/dto/material/request/MaterialClientModifyRequest.java
  src/main/java/com/hmdandelion/project_1410002/purchase/dto/material/request/MaterialOrderCreateRequest.java
  src/main/java/com/hmdandelion/project_1410002/purchase/dto/material/request/MaterialOrderModifyRequest.java
  src/main/java/com/hmdandelion/project_1410002/purchase/dto/material/response/MaterialClientDetailResponse.java
  src/main/java/com/hmdandelion/project_1410002/purchase/dto/material/response/MaterialOrderResponse.java
  src/main/java/com/hmdandelion/project_1410002/purchase/presentation/MaterialClientController.java
  src/main/java/com/hmdandelion/project_1410002/purchase/presentation/MaterialOrderAnalyzeController.java
  src/main/java/com/hmdandelion/project_1410002/purchase/presentation/MaterialOrderController.java
  src/main/java/com/hmdandelion/project_1410002/purchase/service/AssignedMaterialService.java
  src/main/java/com/hmdandelion/project_1410002/purchase/service/MaterialClientService.java
  src/main/java/com/hmdandelion/project_1410002/purchase/service/MaterialOrderAnalyzeService.java
  src/main/java/com/hmdandelion/project_1410002/purchase/service/MaterialOrderService.java
  src/main/java/com/hmdandelion/project_1410002/sales/domain/entity/employee/Department.java
  src/main/java/com/hmdandelion/project_1410002/sales/domain/entity/employee/Employee.java
  src/main/java/com/hmdandelion/project_1410002/sales/domain/entity/employee/Position.java
  src/main/java/com/hmdandelion/project_1410002/sales/domain/repository/client/ClientRepo.java
  src/main/java/com/hmdandelion/project_1410002/sales/domain/repository/client/ClientRepoCustom.java
  src/main/java/com/hmdandelion/project_1410002/sales/domain/repository/client/ClientRepoCustomImpl.java
  src/main/java/com/hmdandelion/project_1410002/sales/domain/repository/employee/EmployeeRepo.java
  src/main/java/com/hmdandelion/project_1410002/sales/domain/repository/employee/EmployeeRepoCustom.java
  src/main/java/com/hmdandelion/project_1410002/sales/domain/repository/employee/EmployeeRepoCustomImpl.java
  src/main/java/com/hmdandelion/project_1410002/sales/dto/request/ClientUpdateRequest.java
  src/main/java/com/hmdandelion/project_1410002/sales/presentation/ClientController.java
  src/main/java/com/hmdandelion/project_1410002/sales/service/ClientService.java
  src/main/java/com/hmdandelion/project_1410002/sales/service/EmployeeService.java
Labels: feature, PR

#52 [PR] 원자재 입고관리
  httpTest/MaterialOrderTest.http
  src/main/java/com/hmdandelion/project_1410002/common/exception/handler/ExceptionHandlingController.java
  src/main/java/com/hmdandelion/project_1410002/common/exception/type/ExceptionCode.java
  src/main/java/com/hmdandelion/project_1410002/inventory/presentation/MaterialAnalyzeController.java
  src/main/java/com/hmdandelion/project_1410002/inventory/service/MaterialAnalyzeService.java
  src/main/java/com/hmdandelion/project_1410002/production/domain/entity/material/MaterialUsage.java
  src/main/java/com/hmdandelion/project_1410002/production/domain/entity/material/MaterialUsageStatus.java
  src/main/java/com/hmdandelion/project_1410002/production/domain/type/MaterialUsageStatus.java
  src/main/java/com/hmdandelion/project_1410002/production/dto/material/MaterialUsageDTO.java
  src/main/java/com/hmdandelion/project_1410002/production/dto/material/StockUsageDTO.java
  src/main/java/com/hmdandelion/project_1410002/production/presentation/MaterialUsageController.java
  src/main/java/com/hmdandelion/project_1410002/purchase/domain/entity/material/MaterialOrder.java
  src/main/java/com/hmdandelion/project_1410002/purchase/domain/repository/material/MaterialOrderRepoCustom.java
  src/main/java/com/hmdandelion/project_1410002/purchase/domain/repository/material/MaterialOrderRepoCustomImpl.java
  src/main/java/com/hmdandelion/project_1410002/purchase/dto/material/response/MaterialOrderWeeklyResponse.java
  src/main/java/com/hmdandelion/project_1410002/purchase/presentation/MaterialOrderController.java
  src/main/java/com/hmdandelion/project_1410002/purchase/service/MaterialClientService.java
  src/main/java/com/hmdandelion/project_1410002/purchase/service/MaterialOrderAnalyzeService.java
  src/main/java/com/hmdandelion/project_1410002/purchase/service/MaterialOrderService.java
Labels: enhancement, feature, PR

#54 [PR] 스프링 시큐리티 로그인 / 로그아웃
  build.gradle
  httpTest/AuthorityTest.http
  httpTest/EstimateTest.http
  httpTest/OrderTest.http
  httpTest/ReturnTest.http
  httpTest/SalesClientTest.http
  src/main/java/com/hmdandelion/project_1410002/auth/config/BeanConfig.java
  src/main/java/com/hmdandelion/project_1410002/auth/config/SecurityConfig.java
  src/main/java/com/hmdandelion/project_1410002/auth/dto/LoginDTO.java
  src/main/java/com/hmdandelion/project_1410002/auth/dto/TokenDTO.java
  src/main/java/com/hmdandelion/project_1410002/auth/filter/CustomAuthenticationFilter.java
  src/main/java/com/hmdandelion/project_1410002/auth/filter/JwtAuthenticationFilter.java
  src/main/java/com/hmdandelion/project_1410002/auth/handler/JwtAccessDeniedHandler.java
  src/main/java/com/hmdandelion/project_1410002/auth/handler/JwtAuthenticationEntryPoint.java
  src/main/java/com/hmdandelion/project_1410002/auth/handler/LoginFailureHandler.java
  src/main/java/com/hmdandelion/project_1410002/auth/handler/LoginSuccessHandler.java
  src/main/java/com/hmdandelion/project_1410002/auth/service/AuthService.java
  src/main/java/com/hmdandelion/project_1410002/auth/type/CustomUser.java
  src/main/java/com/hmdandelion/project_1410002/auth/util/TokenUtils.java
  src/main/java/com/hmdandelion/project_1410002/common/exception/type/ExceptionCode.java
  src/main/java/com/hmdandelion/project_1410002/employee/domain/entity/Authority.java
  src/main/java/com/hmdandelion/project_1410002/employee/domain/entity/Department.java
  src/main/java/com/hmdandelion/project_1410002/employee/domain/entity/Employee.java
  src/main/java/com/hmdandelion/project_1410002/employee/domain/entity/EmployeeAuth.java
  src/main/java/com/hmdandelion/project_1410002/employee/domain/entity/Position.java
  src/main/java/com/hmdandelion/project_1410002/employee/domain/repository/EmployeeRepo.java
  src/main/java/com/hmdandelion/project_1410002/employee/domain/repository/EmployeeRepoCustom.java
  src/main/java/com/hmdandelion/project_1410002/employee/domain/repository/EmployeeRepoCustomImpl.java
  src/main/java/com/hmdandelion/project_1410002/employee/domain/type/AuthorityType.java
  src/main/java/com/hmdandelion/project_1410002/employee/presentation/EmployeeController.java
  src/main/java/com/hmdandelion/project_1410002/employee/service/EmployeeService.java
  src/main/java/com/hmdandelion/project_1410002/production/domain/entity/line/Line.java
  src/main/java/com/hmdandelion/project_1410002/production/domain/entity/production/ProductionDetail.java
  src/main/java/com/hmdandelion/project_1410002/production/domain/repository/productionPlan/WorkOrderRepoCustomImpl.java
  src/main/java/com/hmdandelion/project_1410002/purchase/dto/material/response/MaterialOrderResponse.java
  src/main/java/com/hmdandelion/project_1410002/purchase/service/MaterialOrderService.java
  src/main/java/com/hmdandelion/project_1410002/sales/domain/repository/employee/EmployeeRepo.java
  src/main/java/com/hmdandelion/project_1410002/sales/service/EmployeeService.java
Labels: feature, PR

#55 [PR] 라인관리
  DB/table.sql
  gradlew
  httpTest/LineTest.http
  httpTest/ProductionReportTest.http
  src/main/java/com/hmdandelion/project_1410002/common/exception/type/ExceptionCode.java
  src/main/java/com/hmdandelion/project_1410002/production/domain/entity/line/Line.java
  src/main/java/com/hmdandelion/project_1410002/production/domain/entity/production/ProductionManagement.java
  src/main/java/com/hmdandelion/project_1410002/production/domain/repository/line/LineRepo.java
  src/main/java/com/hmdandelion/project_1410002/production/domain/type/LineStatusType.java
  src/main/java/com/hmdandelion/project_1410002/production/dto/request/LineCreateRequest.java
  src/main/java/com/hmdandelion/project_1410002/production/dto/request/LineUpdateRequest.java
  src/main/java/com/hmdandelion/project_1410002/production/dto/request/ProductionReportCreateRequest.java
  src/main/java/com/hmdandelion/project_1410002/production/dto/request/ProductionReportUpdateRequest.java
  src/main/java/com/hmdandelion/project_1410002/production/dto/response/line/LineResponse.java
  src/main/java/com/hmdandelion/project_1410002/production/dto/response/production/ProductionDetailResponse.java
  src/main/java/com/hmdandelion/project_1410002/production/dto/response/production/ProductionReportResponse.java
  src/main/java/com/hmdandelion/project_1410002/production/presentation/LineController.java
  src/main/java/com/hmdandelion/project_1410002/production/presentation/ProductionManagerController.java
  src/main/java/com/hmdandelion/project_1410002/production/service/LineService.java
  src/main/java/com/hmdandelion/project_1410002/production/service/ProductionService.java
Labels: feature

#66 [PR] 페이지네이션 버그 해결
  src/main/java/com/hmdandelion/project_1410002/sales/domain/repository/client/ClientRepoCustomImpl.java
  src/main/java/com/hmdandelion/project_1410002/sales/domain/repository/estimate/EstimateRepoCustomImpl.java
  src/main/java/com/hmdandelion/project_1410002/sales/domain/repository/order/OrderRepoCustomImpl.java
  src/main/java/com/hmdandelion/project_1410002/sales/domain/repository/returns/ReturnRepoCustomImpl.java
Labels: bug

#70 [PR] 영업판매 파트 Server-side Validation
  src/main/java/com/hmdandelion/project_1410002/common/exception/handler/ExceptionHandlingController.java
  src/main/java/com/hmdandelion/project_1410002/sales/dto/request/ClientCreateRequest.java
  src/main/java/com/hmdandelion/project_1410002/sales/dto/request/ClientUpdateRequest.java
  src/main/java/com/hmdandelion/project_1410002/sales/dto/request/EstimateCreateRequest.java
  src/main/java/com/hmdandelion/project_1410002/sales/dto/request/EstimateProductRequest.java
  src/main/java/com/hmdandelion/project_1410002/sales/dto/request/EstimateUpdateRequest.java
  src/main/java/com/hmdandelion/project_1410002/sales/dto/request/ReturnCreateRequest.java
  src/main/java/com/hmdandelion/project_1410002/sales/dto/request/ReturnProductRequest.java
  src/main/java/com/hmdandelion/project_1410002/sales/dto/response/OrdersResponse.java
  src/main/java/com/hmdandelion/project_1410002/sales/presentation/ClientController.java
  src/main/java/com/hmdandelion/project_1410002/sales/presentation/EstimateController.java
  src/main/java/com/hmdandelion/project_1410002/sales/presentation/ReturnController.java
Labels: enhancement, feature

#76 [PR] 예외 핸들링 및 status 추가
  src/main/java/com/hmdandelion/project_1410002/common/exception/type/ExceptionCode.java
  src/main/java/com/hmdandelion/project_1410002/sales/domain/type/OrderStatus.java
  src/main/java/com/hmdandelion/project_1410002/sales/service/EstimateService.java
Labels: enhancement

#74 [PR] 원자재 스펙 상세 조회
  httpTest/MaterialSpecTest.http
  src/main/java/com/hmdandelion/project_1410002/auth/config/SecurityConfig.java
  src/main/java/com/hmdandelion/project_1410002/inventory/dto/material/response/SpecDetailResponse.java
  src/main/java/com/hmdandelion/project_1410002/inventory/presentation/MaterialSpecController.java
  src/main/java/com/hmdandelion/project_1410002/inventory/service/MaterialSpecService.java
  src/main/java/com/hmdandelion/project_1410002/purchase/domain/repository/material/AssignedMaterialRepo.java
  src/main/java/com/hmdandelion/project_1410002/purchase/dto/material/response/MaterialOrderResponse.java
  src/main/java/com/hmdandelion/project_1410002/purchase/service/AssignedMaterialService.java
  src/main/java/com/hmdandelion/project_1410002/purchase/service/MaterialClientService.java
  src/main/java/com/hmdandelion/project_1410002/purchase/service/MaterialOrderService.java
  src/main/java/com/hmdandelion/project_1410002/sales/domain/repository/client/ClientRepo.java
  src/main/java/com/hmdandelion/project_1410002/sales/service/ClientService.java
Labels: bug, enhancement, feature

#80 [PR] 반품 조회 버그 수정
  src/main/java/com/hmdandelion/project_1410002/sales/domain/repository/returns/ReturnRepoCustomImpl.java
  src/main/java/com/hmdandelion/project_1410002/sales/domain/type/ManageStatus.java
Labels: bug

#81 Refactor/62 release
  src/main/java/com/hmdandelion/project_1410002/auth/config/SecurityConfig.java
  src/main/java/com/hmdandelion/project_1410002/employee/domain/repository/EmployeeRepo.java
  src/main/java/com/hmdandelion/project_1410002/employee/presentation/EmployeeController.java
  src/main/java/com/hmdandelion/project_1410002/employee/service/EmployeeService.java
  src/main/java/com/hmdandelion/project_1410002/inventory/domian/entity/product/Product.java
  src/main/java/com/hmdandelion/project_1410002/inventory/domian/repository/product/BomRepo.java
  src/main/java/com/hmdandelion/project_1410002/inventory/domian/repository/product/ProductSpecRepo.java
  src/main/java/com/hmdandelion/project_1410002/inventory/domian/repository/stock/StockRepo.java
  src/main/java/com/hmdandelion/project_1410002/inventory/domian/repository/stock/StockRepoCustomImpl.java
  src/main/java/com/hmdandelion/project_1410002/inventory/domian/repository/stock/StorageRepoCustom.java
  src/main/java/com/hmdandelion/project_1410002/inventory/domian/repository/stock/StorageRepoCustomImpl.java
  src/main/java/com/hmdandelion/project_1410002/inventory/dto/product/response/ProductSpecResponse.java
  src/main/java/com/hmdandelion/project_1410002/inventory/dto/release/response/ReleasePossible.java
  src/main/java/com/hmdandelion/project_1410002/inventory/dto/stock/response/LeftStockDTO.java
  src/main/java/com/hmdandelion/project_1410002/inventory/dto/stock/response/ReleaseShippingDTO.java
  src/main/java/com/hmdandelion/project_1410002/inventory/dto/stock/response/ReleaseWaitDTO.java
  src/main/java/com/hmdandelion/project_1410002/inventory/dto/stock/response/StorageWarehouseDTO.java
  src/main/java/com/hmdandelion/project_1410002/inventory/dto/stock/response/TodayStockDTO.java
  src/main/java/com/hmdandelion/project_1410002/inventory/presentation/BomController.java
  src/main/java/com/hmdandelion/project_1410002/inventory/presentation/MaterialSpecController.java
  src/main/java/com/hmdandelion/project_1410002/inventory/presentation/ProductController.java
  src/main/java/com/hmdandelion/project_1410002/inventory/presentation/ProductSpecController.java
  src/main/java/com/hmdandelion/project_1410002/inventory/presentation/ReleaseController.java
  src/main/java/com/hmdandelion/project_1410002/inventory/presentation/StockController.java
  src/main/java/com/hmdandelion/project_1410002/inventory/presentation/StorageController.java
  src/main/java/com/hmdandelion/project_1410002/inventory/service/BomService.java
  src/main/java/com/hmdandelion/project_1410002/inventory/service/MaterialSpecService.java
  src/main/java/com/hmdandelion/project_1410002/inventory/service/ProductService.java
  src/main/java/com/hmdandelion/project_1410002/inventory/service/ProductSpecService.java
  src/main/java/com/hmdandelion/project_1410002/inventory/service/ReleaseService.java
  src/main/java/com/hmdandelion/project_1410002/inventory/service/StockService.java
  src/main/java/com/hmdandelion/project_1410002/inventory/service/StorageService.java
  src/main/java/com/hmdandelion/project_1410002/production/service/WorkOrderService.java
Labels: enhancement, PR

#82 [PR] Auth설정
  src/main/java/com/hmdandelion/project_1410002/auth/config/SecurityConfig.java
Labels: feature, PR
